import { useState } from "react";
import type { CoverageResult } from "../api/diagnostics";
import { downloadLayer, downloadManifest, downloadReport, type ReportOptions } from "../api/restitution";
import type { TerritoryProfile } from "../api/territories";

export function ReportStudio({ territory, diagnostic, layerId, layerName, onClose }: { territory: TerritoryProfile; diagnostic: CoverageResult; layerId: string; layerName: string; onClose: () => void }) {
  const [options, setOptions] = useState<ReportOptions>({ title: "Diagnostic de couverture territoriale", template: "a4_portrait", author: "Mamadou Ndiaye LO", includeDetails: true, includeMethodology: true, includeSources: true });
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const execute = async (name: string, operation: () => Promise<void>) => { setBusy(name); setError(null); try { await operation(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Export impossible."); } finally { setBusy(null); } };
  const update = <K extends keyof ReportOptions>(key: K, value: ReportOptions[K]) => setOptions((current) => ({ ...current, [key]: value }));
  return <section className="report-studio">
    <header><div><span>STUDIO DE RESTITUTION</span><h2>Composer un livrable décisionnel</h2></div><button onClick={onClose}>×</button></header>
    <div className="report-layout"><div className="report-settings"><label>Titre du rapport<input value={options.title} onChange={(event) => update("title", event.target.value)} /></label><label>Auteur<input value={options.author} onChange={(event) => update("author", event.target.value)} /></label><strong>Format d’impression</strong><div className="template-grid">{([['a4_portrait','A4','Portrait'],['a4_landscape','A4','Paysage'],['a3_landscape','A3','Grand format']] as const).map(([value, size, label]) => <button key={value} className={options.template === value ? "active" : ""} onClick={() => update("template", value)}><i className={value} /><b>{size}</b><small>{label}</small></button>)}</div><strong>Blocs du modèle</strong><div className="block-options"><label><input type="checkbox" checked={options.includeDetails} onChange={(event) => update("includeDetails", event.target.checked)} /> Tableau détaillé</label><label><input type="checkbox" checked={options.includeMethodology} onChange={(event) => update("includeMethodology", event.target.checked)} /> Méthode et limites</label><label><input type="checkbox" checked={options.includeSources} onChange={(event) => update("includeSources", event.target.checked)} /> Sources et auteur</label></div></div>
      <div className="report-preview"><div className={`paper ${options.template}`}><span>GEODASHBOARD · NOTE DÉCISIONNELLE</span><h3>{options.title}</h3><p>{territory.name} · INSEE {territory.code}</p><div className="preview-kpis"><b>{diagnostic.current.coverage_rate.toFixed(1)}%</b><b>{diagnostic.scenario.coverage_rate.toFixed(1)}%</b><b>+{diagnostic.gain_points.toFixed(1)} pts</b></div><div className="preview-maps"><i /><i /></div><div className="preview-decision">{diagnostic.interpretation}</div>{options.includeDetails && <div className="preview-lines"><i/><i/><i/></div>}</div><small>Aperçu de composition · le PDF final contient la carte vectorielle et les valeurs complètes.</small></div></div>
    <footer><div><button onClick={() => void execute("geojson", () => downloadLayer(layerId, "geojson"))}>GeoJSON</button><button onClick={() => void execute("gpkg", () => downloadLayer(layerId, "gpkg"))}>GeoPackage</button><button onClick={() => void execute("manifest", downloadManifest)}>Manifeste JSON</button></div><button className="generate-report" disabled={busy !== null} onClick={() => void execute("pdf", () => downloadReport(options, territory, diagnostic, layerName))}>{busy === "pdf" ? "Génération…" : "Générer le PDF"}</button>{error && <p>{error}</p>}</footer>
  </section>;
}
